
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button boton1;
	private global::Gtk.Button boton2;
	private global::Gtk.Button boton4;
	private global::Gtk.Label numero1;
	private global::Gtk.Label numero2;
	private global::Gtk.Label resultado;
	private global::Gtk.Entry barra1;
	private global::Gtk.Entry barra2;
	private global::Gtk.Entry barra3;
	private global::Gtk.Button boton3;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.boton1 = new global::Gtk.Button ();
		this.boton1.CanFocus = true;
		this.boton1.Name = "boton1";
		this.boton1.UseUnderline = true;
		this.boton1.Label = global::Mono.Unix.Catalog.GetString ("sumar");
		this.fixed1.Add (this.boton1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.boton1]));
		w1.X = 36;
		w1.Y = 162;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.boton2 = new global::Gtk.Button ();
		this.boton2.CanFocus = true;
		this.boton2.Name = "boton2";
		this.boton2.UseUnderline = true;
		this.boton2.Label = global::Mono.Unix.Catalog.GetString ("restar");
		this.fixed1.Add (this.boton2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.boton2]));
		w2.X = 110;
		w2.Y = 163;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.boton4 = new global::Gtk.Button ();
		this.boton4.CanFocus = true;
		this.boton4.Name = "boton4";
		this.boton4.UseUnderline = true;
		this.boton4.Label = global::Mono.Unix.Catalog.GetString ("dividir");
		this.fixed1.Add (this.boton4);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.boton4]));
		w3.X = 260;
		w3.Y = 163;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numero1 = new global::Gtk.Label ();
		this.numero1.Name = "numero1";
		this.numero1.LabelProp = global::Mono.Unix.Catalog.GetString ("numero1");
		this.fixed1.Add (this.numero1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.numero1]));
		w4.X = 31;
		w4.Y = 24;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numero2 = new global::Gtk.Label ();
		this.numero2.Name = "numero2";
		this.numero2.LabelProp = global::Mono.Unix.Catalog.GetString ("numero2");
		this.fixed1.Add (this.numero2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.numero2]));
		w5.X = 31;
		w5.Y = 58;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.resultado = new global::Gtk.Label ();
		this.resultado.Name = "resultado";
		this.resultado.LabelProp = global::Mono.Unix.Catalog.GetString ("resultado");
		this.fixed1.Add (this.resultado);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.resultado]));
		w6.X = 32;
		w6.Y = 91;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.barra1 = new global::Gtk.Entry ();
		this.barra1.CanFocus = true;
		this.barra1.Name = "barra1";
		this.barra1.IsEditable = true;
		this.barra1.InvisibleChar = '●';
		this.fixed1.Add (this.barra1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.barra1]));
		w7.X = 106;
		w7.Y = 14;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.barra2 = new global::Gtk.Entry ();
		this.barra2.CanFocus = true;
		this.barra2.Name = "barra2";
		this.barra2.IsEditable = true;
		this.barra2.InvisibleChar = '●';
		this.fixed1.Add (this.barra2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.barra2]));
		w8.X = 108;
		w8.Y = 52;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.barra3 = new global::Gtk.Entry ();
		this.barra3.CanFocus = true;
		this.barra3.Name = "barra3";
		this.barra3.IsEditable = true;
		this.barra3.InvisibleChar = '●';
		this.fixed1.Add (this.barra3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.barra3]));
		w9.X = 108;
		w9.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.boton3 = new global::Gtk.Button ();
		this.boton3.CanFocus = true;
		this.boton3.Name = "boton3";
		this.boton3.UseUnderline = true;
		this.boton3.Label = global::Mono.Unix.Catalog.GetString ("multiplicar");
		this.fixed1.Add (this.boton3);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.boton3]));
		w10.X = 174;
		w10.Y = 162;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.boton1.Clicked += new global::System.EventHandler (this.OnBoton1Clicked);
		this.boton2.Clicked += new global::System.EventHandler (this.OnBoton2Clicked);
		this.boton4.Clicked += new global::System.EventHandler (this.OnBoton4Clicked);
		this.boton3.Clicked += new global::System.EventHandler (this.OnBoton3Clicked);
	}
}
